### ISSUE TITLE
Help Planning and Tracking Progress

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-contracts#443]
We want to make planing transparent and track progress over all Raiden Teams. Therefore, we need information from Team Smart Contract in [this document](https://docs.google.com/presentation/d/17snEGy2QO4Qk1RjKn7h_rhzwtk7yE046h9_b2D9FE90/edit#slide=id.g4c5176c171_0_57) on slide 3.
We need in particular (could you just add to slide 3):
- [ ] sub-goals of the Ithaca milestone (the subgoals together should add up to what you want to achieve for Ithaca)
- [ ] Number of open issues and / or user stories towards Ithaca
- [ ] Number of closed issues and / or user stories towards Ithaca
- [ ] Mayor critical dependencies to other teams or decisions you see within Ithaca
- [ ] A link to your "backlog" or collection of all Issues regarding team Team Smart Contract and Ithaca

Please reach out in case you have any questions!

**Comment by loredanacirstea** [comment]
@Dominik1999 :

The issues themselves are well documented and labeled.

# Ithaca Milestone 

## Issues:

- https://github.com/raiden-network/raiden-contracts/milestone/2. `P1` and `P2` are important. `P3` are optional.
- Current sub-milestone: https://github.com/raiden-network/raiden-contracts/milestone/13

### Important Subgoals:

- [Minimal code splitting for TokenNetwork - using a library for pure functions](https://github.com/raiden-network/raiden-contracts/issues/401)
- [Keep networks alive between bounty releases and actual release - limits switch](https://github.com/raiden-network/raiden-contracts/issues/391) **will need legal review of the spec when ready to be proposed**
- [Reenable setTotalWithdraw](https://github.com/raiden-network/raiden-contracts/issues/277) **when the Raiden Client Team is ready to implement it, we just remove the comments**
- [Add batching of transactions for opening a channel & depositing ](https://github.com/raiden-network/raiden-contracts/issues/400) - not priority objective, but it was requested by @hackaugusto 

The rest of the issues are improvements to our python scripts/testing etc.

**Comment by loredanacirstea** [comment]
@Dominik1999 this above does not include the RSB specs, which you and @palango need to agree/decide about.

**Comment by Dominik1999** [comment]
ok thanks! Can you or @palango open a issue about that - we can then specify the issue, when we have the respective content / specification

**Comment by pirapira** [comment]
I'll give a shot at this.

**Comment by pirapira** [comment]
As of 2019-02-05:

**sub-goals**
* review and include service contracts
* deploy scripts and process for service contracts
* deploy all contracts on test net in timely manners
* set up deployment procedure (for main net)

**number of open issues**

13

**number of closed issues**

29

**major critical dependencies**

Service contracts to be written.

**backlog**

https://github.com/raiden-network/raiden-contracts/issues

@Dominik1999 please close this issue if these work for you.

**Comment by pirapira** [comment]
@Dominik1999 please close this issue if the planning is working.  Otherwise please give reasons why this issue should stay open.

**Comment by Dominik1999** [comment]
thanks, planning works. Let's talk about feedback tomorrow
