### ISSUE TITLE
Service contracts testing for Alderaan

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#537]
This issue keeps track of the overall service contract testing for Ithaca MVP.

* [x] happy case test cases for MS, UDC and OneToN https://github.com/raiden-network/raiden-contracts/issues/569 https://github.com/raiden-network/raiden-contracts/issues/570 https://github.com/raiden-network/raiden-contracts/issues/571
* [ ] error cases for MS, UDC and OneToN https://github.com/raiden-network/raiden-contracts/issues/572 https://github.com/raiden-network/raiden-contracts/issues/573 https://github.com/raiden-network/raiden-contracts/issues/574
* [x] happy case test cases for ServiceRegistry https://github.com/raiden-network/raiden-contracts/issues/580
* [x] unhappy cases for ServiceRegistry https://github.com/raiden-network/raiden-contracts/issues/581

The test implementation should be tracked in each issue.  When all finish, this issue can be closed.

**Comment by karlb** [comment]
We have separate issues for the remaining tasks.
